### PR TITLE
Allow to disable CSRF check during the oauth login.

### PR DESCRIPTION
**Pull request by babayotakun**

### CODE REVIEW

**Review by eviltrout — APPROVED** [review]
This seems good to me.

**Comment by eviltrout** [comment]
Thanks!

**Comment by eviltrout** [comment]
@babayotakun Actually there is some concern on our side that people will make their sites less secure by enabling this. What was the reasoning for the change? It seems to violate the spec.

**Comment by babayotakun** [comment]
We have a closed oauth2 ecosystem with custom oauth2 provider and to this day we haven't implemented 'state' parameter (and highly likely it won't happen at all). So we need a simple way to turn this off.

**Comment by eviltrout** [comment]
Thanks @babayotakun - I think the setting needs to be hidden at least. I'm going to add a follow up to do this.

**Pull request merged**
